version: '3.8'

services:
  # Temporal Workflow Engine
  temporal:
    image: temporalio/auto-setup:latest
    ports:
      - "7233:7233"
      - "8088:8088"
    environment:
      - LOG_LEVEL=info
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    volumes:
      - temporal_data:/var/temporal
    networks:
      - nexus_network
    restart: unless-stopped

  # Neo4j Knowledge Graph
  neo4j:
    image: neo4j:5.15
    ports:
      - "7474:7474"  # Browser
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/nexusrsi123
      - NEO4J_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - nexus_network
    restart: unless-stopped

  # Ollama LLM Server
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - nexus_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G

  # Grafana Monitoring
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=nexusrsi
      - GF_INSTALL_PLUGINS=redis-datasource,vertamedia-clickhouse-datasource
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - nexus_network
    restart: unless-stopped

  # Prometheus Metrics
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - nexus_network
    restart: unless-stopped

networks:
  nexus_network:
    driver: bridge

volumes:
  temporal_data:
  neo4j_data:
  neo4j_logs:
  ollama_data:
  grafana_data:
  prometheus_data: